# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: datree-cli
release:
  prerelease: auto
before:
  hooks:
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    binary: datree
    id: datree
    goos:
      - linux
    main: ./main.go
    flags:
      - -tags={{.Env.DATREE_DEPLOYMENT}}
    ldflags:
      - -X github.com/datreeio/datree/cmd.CliVersion={{.Env.DATREE_BUILD_VERSION}}
  - env:
      - CGO_ENABLED=0
    binary: datree
    id: datree-macos
    goos:
      - darwin
    main: ./main.go
    flags:
      - -tags={{.Env.DATREE_DEPLOYMENT}}
    ldflags:
      - -X github.com/datreeio/datree/cmd.CliVersion={{.Env.DATREE_BUILD_VERSION}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
    format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
blobs:
  # You can have multiple blob config
  -
    # Template for the cloud provider name
    # s3 for AWS S3 Storage
    provider: s3

    # Sets the bucket region.
    # Requires provider to be `s3`
    # Defaults to empty.
    region: us-west-1

    # Disables SSL
    # Requires provider to be `s3`
    # Defaults to false
    disableSSL: true

    # Template for the bucket name
    bucket: yishay-test

    # Template for the path/name inside the bucket.
    # Default is `{{ .ProjectName }}/{{ .Tag }}`
    folder: "test-upload"
