language: go

go:
- 1.x

script:
  - go build -tags $DATREE_DEPLOYMENT
  - curl -sfL https://git.io/goreleaser | VERSION=v$GORELEASER_VERSION sh -s -- check

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=0.1.$TRAVIS_BUILD_NUMBER-$TRAVIS_BRANCH
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git remote set-url origin https://datree-ci:$GITHUB_TOKEN@github.com/datreeio/datree.git
  - git push --tags
  - ls -R
  - git stash save --keep-index --include-untracked

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | VERSION=v$GORELEASER_VERSION bash
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(staging)$

env:
  global:
    # GITHUB_TOKEN
    - secure: "ircKrCahc3fh1uufpwGDVcCu7oYx2awf4ZUyJeyWE7TmmW5BpY+1+yuppiyeYNDk6Lgq5mN/N19rNMLzGKFJtYIEXsN0iZI+YmSEXOTiKFH/Nze2a9PKZw5Ht3aCwrq+xRIrQEiSaRDQOGHxnH0OtGnlO+pMLqnnv+Szb2zsYc1/fIktJKfsAQdPPSONW2DnaNe5mJUdTH56OsHoDxSak6y8cqBcKZe1UwmQi+y1tzSdVZAkAOOpRpvPZu1qC4XwYeSyG0EFkYcUfmVg7GrwoCx9U71Unuk+wMuuPASiSIgLRT5xwfhIjDWYjR0lTE1wFtIV57CvrwqTi3oEXxRrvtT46AsUSOuJlaYNBIa/cgIieE+/fODy4C72RI2qzSzPS3AyYryVSb2nNmHXWtLYulHfNxx15B42UYeOWR3JRp14UNBZY6xM0Dqfj2SNeSqpRydVQR6TWiHg3fIh1fH+GHXMix8+3Jhp1a0fmgqw8akVeWwzKMx4+qZNN/H8BpSeoaKCOLWhodgFV0eQDKZ2YRGv+6s9Z3n0AbD1dflcY44CXxDmfi4MiXNWj5T1XjWTv6F9gn4np4dsMxTyyysjQv7Oo57BDA7/V7K1Qa9wP0FjUxDvaAAJ5qe2AEU30JK/eV8fUEaA+Eh4Jr+3OWCctgV6ngN/NIKZQ0Qceswp43I="
    - GORELEASER_VERSION="0.157.0"
    - DATREE_DEPLOYMENT=$TRAVIS_BRANCH
